		<link rel="stylesheet" href="css/footer.css">
		<hr id="footerTopLine">
		<footer>
			<h2><a href="index.html"><img src="index_img/footer_logo.png" alt="서울사진영상IT학원 로고"></a></h2>
			<p>
				사업자등록번호 : 201-86-23600  |  개인정보보호방침<br>
				서울 강남구 역삼동 831-32번지 (역삼로 1길 18)  동원빌딩 5층    대표자  김동현<br>
				Copyright 2001  ⓒ 서울사진영상IT학원   All Rights Reserved. 
			</p>
			<div>			
				<a href ="tel:02-561-2434" class="material-icons footerPhone">phone_in_talk</a>
				<b>상담문의</b>  <a href ="tel:02-561-2434"><strong>02.561.2434</strong></a><br>
				<b>강 남 점</b> 교육 . 문화 . 교통의 중심   강남역 4번 출구<br>
				<b>상담시간</b>  평일 12시 30분 ~ 8시30분 &#9829; 토/일요일  11시~6시
			</div>
		</footer>