<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">

<title>서울사진영상IT학원</title>

<link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Nanum+Gothic:wght@400;700&family=Noto+Sans+KR:wght@100;300;400&family=Roboto:wght@300;400&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" rel="stylesheet">

<link rel="stylesheet" href="css/top.css">

<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="js/navi.js"></script>
</head>
<body>

		<header>
			<p><b>20년 </b>전통의 <b>노하우</b></p>
			<div>
				<button class="material-icons menu">menu</button>
				<h2 id="logo"><a href="index.html" rel="external"><img src="index_img/top_logo.jpg" alt="서울사진영상IT학원 로고"></a></h2>
				<h3>
					<a href ="tel:02-561-2434" class="telNum">02-561-2434</a>
					<a href ="tel:02-561-2434" class="material-icons phone">phone_in_talk</a>
				</h3>
			</div>
		</header>
		<nav id="menuAll">
			<div id="subMenuBg"></div>
			<hr>		
			<ul>
				<li>
					<a href="#" class="mainMenu">
						학원소개
						<i class="material-icons more">expand_more</i>
						<hr>
					</a>
					<nav class="subMenu">
						<a href="academy_index.html" rel="external">학원안내</a>
						<a href="#">강사진</a>
						<a href="#">상담실</a>
						<a href="#">오시는 길</a>
						<a href="#">국비지원이란?</a>
					</nav>
				</li>
				<li>
					<a href="#" class="mainMenu">
						사진과정안내
						<i class="material-icons more">expand_more</i>
						<hr>
					</a>
					<nav class="subMenu">
						<a href="photo_course.html" rel="external">구직자과정</a>
						<a href="#">재직자저녁과정</a>
						<a href="#">재직자주말과정</a>
						<a href="#">일반과정</a>
					</nav>
				</li>
				<li>
					<a href="#" class="mainMenu">
						영상과정안내
						<i class="material-icons more">expand_more</i>
						<hr>
					</a>
					<nav class="subMenu">
						<a href="video_course.html" rel="external">구직자과정</a>
						<a href="#">재직자저녁과정</a>
						<a href="#">재직자주말과정</a>
					</nav>
				</li>
				<li>
					<a href="#" class="mainMenu">
						웹디자인과정안내
						<i class="material-icons more">expand_more</i>
						<hr>
					</a>
					<nav class="subMenu">
						<a href="web_course.html">구직자과정</a>
						<a href="#">재직자저녁과정</a>
						<a href="#">재직자주말과정</a>
					</nav>
				</li>
				<li>
					<a href="#" class="mainMenu">
						졸업생작품
						<i class="material-icons more">expand_more</i>
						<hr>
					</a>
					<nav class="subMenu">
						<a href="gallery.html">사진과정</a>
						<a href="#">영상과정</a>
						<a href="#">홈페이지과정</a>
					</nav>
				</li>
				<li>
					<a href="question.html" rel="external" class="mainMenu">상담실<hr></a>
				</li>
				<li>
					<a href="map.html" rel="external" class="mainMenu">오시는길<hr></a>
				</li>
			</ul>
		</nav>